// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oawadcsasvrxovqlaxue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hd2FkY3Nhc3ZyeG92cWxheHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjMwNjksImV4cCI6MjA3MTgzOTA2OX0.YZA_dqRQDLuxZfWOW2c0LXTSzosNx30yehZJdhaT6M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});